# Simple Arithmetic

#### You could use arithmetic operators [ + , - , * , / ] directly between NumPy arrays,
#### but this section discusses an extension of the same where we have functions that can take any array-like objects e.g. lists, tuples etc.
#### and perform arithmetic conditionally

# Addition - الجمع

In [1]:
# The add() function sums the content of two arrays, and return the results in a new array.

import numpy as np

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


# Subtraction - الطرح

In [2]:
# The subtract() function subtracts the values from one array with the values from another array, and return the results in a new array.

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


# Multiplication - الضرب

In [3]:
# The multiply() function multiplies the values from one array with the values from another array, and return the results in a new array.

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


# Division - القسمة

In [4]:
# The divide() function divides the values from one array with the values from another array, and return the results in a new array.

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


# Power - الأس

In [5]:
# The power() function rises the values from the first array to the power of the values of the second array, and return the results in a new array.

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)
# The example above will return [1000 3200000 729000000 6553600000000 2500 0] which is the result of 10*10*10, 20*20*20*20*20, 30*30*30*30*30*30 etc.



[      1000    3200000  729000000 -520093696       2500          0]


# Remainder - بقية

In [6]:
# Both the mod() and the remainder() functions return the remainder of the values in the first array corresponding to the values in the second array, and return the results in a new array.

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)
# The example above will return [1 6 3 0 0 27] which is the remainders when you divide 10 with 3 (10%3), 20 with 7 (20%7) 30 with 9 (30%9) etc.

[ 1  6  3  0  0 27]


In [7]:
# You get the same result when using the remainder() function:

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.remainder(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


# Quotient and Mod - حاصل القسمة و المصفوفة

In [10]:
#الاول حاصر القسمه و الثانى المصفوفه
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)
#The first array represents the quotients, (the integer value when you divide 10 with 3, 20 with 7, 30 with 9 etc.
#The second array represents the remainders of the same divisions.

(array([ 3,  2,  3,  5, 25,  1], dtype=int32), array([ 1,  6,  3,  0,  0, 27], dtype=int32))


# Absolute Values - القيمة االمطلقة

In [11]:
# Both the absolute() and the abs() functions functions do the same absolute operation element-wise but we should use absolute() to avoid confusion with python's inbuilt math.abs()

import numpy as np

arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)
# The example above will return [1 2 1 2 3 4].



[1 2 1 2 3 4]
