# SCORPION

## Random Intro

In [1]:
from numpy import random

In [2]:
x = random.randint(100) #الناتج اى رقم ما بين ال100 و ال0

In [3]:
print(x)

68


## Generate random float

In [4]:
x = random.rand() #في هذه الحاله سيعطى رقم عشوائي نوعه float
print(x)

0.9048352237726583


## Generate Random Array

In [5]:
x = random.randint(100 , size=(5)) #مصفوفه فيها خمس عناصر قيمتهم تتراوح من 0 ال 100
print(x)

[99 63 95 85 96]


In [8]:
x = random.rand(100) #مصفوفه فيها 100 رقم من النوع float
print(x)

[0.93179485 0.76899729 0.40066336 0.17949698 0.30190913 0.26969021
 0.92568125 0.52107803 0.67538241 0.76092007 0.99679214 0.42276254
 0.5183902  0.4376446  0.43407704 0.45462291 0.35172687 0.92786374
 0.67185498 0.84864463 0.87422678 0.87808127 0.52619042 0.19346314
 0.90141718 0.55642774 0.65558879 0.97573802 0.7525513  0.00338897
 0.78495489 0.18810006 0.86289119 0.20035094 0.70196883 0.44311465
 0.60080368 0.89587061 0.24191404 0.87201369 0.41670968 0.53496492
 0.75624032 0.60663098 0.44550334 0.03592334 0.77278517 0.47992656
 0.24341226 0.67728242 0.8527828  0.66331917 0.48953417 0.70703114
 0.39995782 0.74215663 0.99104184 0.93298639 0.21771982 0.70306709
 0.7270845  0.83324547 0.01093835 0.4815674  0.59645022 0.83876866
 0.30485107 0.54611112 0.96921434 0.1465176  0.56499425 0.34834866
 0.83720951 0.49767636 0.89492121 0.13975824 0.41141836 0.21832616
 0.40390779 0.56964909 0.74370968 0.02086223 0.3670975  0.35455119
 0.74283241 0.30982791 0.78947495 0.18846488 0.82408302 0.5429

In [9]:
x = random.rand(3,5) # مصفوفه بها 3 مصفوفها كل مصفوفه تحتوى علي 5 ارقام من النوع float
print(x)

[[0.19965941 0.94094484 0.30105308 0.75700582 0.13414213]
 [0.69770333 0.84220598 0.65601197 0.54885385 0.23844606]
 [0.88421273 0.95404797 0.21481096 0.19745812 0.63020529]]


## Generate Random Number From Array

In [11]:
x = random.choice([3, 5, 7, 9]) #توليد رقم عشوائي من المصفوفة
print(x)

5


In [13]:
#ايضا ممكن استعمال الداله size
x = random.choice([3, 5, 7, 9], size=(3, 5)) #مصفوفه بها 3 مصفوفات كل مصفوفه تحتوى علي 5عناصر عشوائيه من المصفوفه 
print(x)

[[5 5 7 9 3]
 [7 7 7 7 3]
 [9 3 5 7 7]]
